/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "/Users/jkb/Work/whatsapp/client/iphone/release/2_10_1/.h"

#import "MFMailComposeViewControllerDelegate-Protocol.h"
#import "MFMessageComposeViewControllerDelegate-Protocol.h"
#import "UIActionSheetDelegate-Protocol.h"
#import "WAMediaSource-Protocol.h"

@class NSMutableArray, NSMutableString, NSString, UIButton, UILabel, UITableView, UIView, WAProgressHUD, WAThumbsViewController;

@interface PersonViewController : /Users/jkb/Work/whatsapp/client/iphone/release/2_10_1/ <UIActionSheetDelegate, MFMailComposeViewControllerDelegate, MFMessageComposeViewControllerDelegate, WAMediaSource>
{
    UITableView *_tableViewMain;
    UIView *_headerView;
    UIButton *_buttonProfilePhoto;
    UIView *_titlesView;
    UILabel *_textLabelFullName;
    UILabel *_textLabelPhonetic;
    UILabel *_textLabelNickname;
    UILabel *_textLabelJob;
    UILabel *_textLabelCompany;
    int _displayedContactID;
    NSString *_highlightedWhatsAppID;
    int _mediaCount;
    NSMutableArray *_mediaObjects;
    BOOL _loadingMedia;
    NSMutableArray *_personData;
    NSMutableArray *_phonesForFavs;
    NSMutableArray *_phonesForChat;
    NSMutableArray *_phonesWithChatHistory;
    NSMutableArray *_contactEmails;
    NSMutableString *_contactName;
    unsigned int _selectedPhoneIndex;
    BOOL _showTableFooter;
    BOOL _enableClearButton;
    WAProgressHUD *_progressHUD;
    WAThumbsViewController *_thumbsViewController;
}

+ (id)sharedTimePeriodFormatter;
+ (id)sharedDateFormatter;
+ (id)sharedDateTimeFormatter;
- (void)setTextLabelCompany:(id)fp8;
- (id)textLabelCompany;
- (void)setTextLabelJob:(id)fp8;
- (id)textLabelJob;
- (void)setTextLabelNickname:(id)fp8;
- (id)textLabelNickname;
- (void)setTextLabelPhonetic:(id)fp8;
- (id)textLabelPhonetic;
- (void)setTextLabelFullName:(id)fp8;
- (id)textLabelFullName;
- (void)setTitlesView:(id)fp8;
- (id)titlesView;
- (void)setButtonProfilePhoto:(id)fp8;
- (id)buttonProfilePhoto;
- (void)setHeaderView:(id)fp8;
- (id)headerView;
- (void)setTableViewMain:(id)fp8;
- (id)tableViewMain;
- (void).cxx_destruct;
- (void)applicationWillResignActive:(id)fp8;
- (void)chatStorage:(id)fp8 didUpdateChatSession:(id)fp12;
- (void)chatStorageDidDeleteChatSessions:(id)fp8;
- (void)deleteMediaAtIndexes:(id)fp8;
- (id)mediaObjectAtIndex:(unsigned int)fp8;
- (unsigned int)numberOfMediaObjects;
- (id)sourceTitle;
- (void)resetMediaData;
- (void)loadMediaData;
- (BOOL)dataReady;
- (void)viewAllMedia;
- (void)loadThumbsViewController;
- (void)countMedia;
- (void)messageComposeViewController:(id)fp8 didFinishWithResult:(int)fp12;
- (void)mailComposeController:(id)fp8 didFinishWithResult:(int)fp12 error:(id)fp16;
- (void)actionSheet:(id)fp8 clickedButtonAtIndex:(int)fp12;
- (void)chatWithContact;
- (void)startChatWithPhoneID:(id)fp8 contact:(id)fp12;
- (id)tableView:(id)fp8 titleForHeaderInSection:(int)fp12;
- (id)tableView:(id)fp8 viewForHeaderInSection:(int)fp12;
- (float)tableView:(id)fp8 heightForHeaderInSection:(int)fp12;
- (void)tableView:(id)fp8 didSelectRowAtIndexPath:(id)fp12;
- (id)tableView:(id)fp8 willSelectRowAtIndexPath:(id)fp12;
- (int)tableView:(id)fp8 editingStyleForRowAtIndexPath:(id)fp12;
- (id)tableView:(id)fp8 cellForRowAtIndexPath:(id)fp12;
- (void)tableView:(id)fp8 willDisplayCell:(id)fp12 forRowAtIndexPath:(id)fp16;
- (float)tableView:(id)fp8 heightForRowAtIndexPath:(id)fp12;
- (int)tableView:(id)fp8 numberOfRowsInSection:(int)fp12;
- (int)numberOfSectionsInTableView:(id)fp8;
- (void)setContactID:(int)fp8 whatsappID:(id)fp12;
- (BOOL)shouldAutorotateToInterfaceOrientation:(int)fp8;
- (void)viewDidDisappear:(BOOL)fp8;
- (void)viewDidAppear:(BOOL)fp8;
- (void)viewWillAppear:(BOOL)fp8;
- (void)viewDidUnload;
- (void)viewDidLoad;
- (void)addToFavorites;
- (void)addPhoneToFavorites:(id)fp8;
- (void)clearChatHistory;
- (void)emailChatHistory;
- (void)askToAttachMedia;
- (void)emailChatHistoryWithMedia:(BOOL)fp8;
- (void)inviteContact;
- (void)inviteViaSMS;
- (void)emailToAddress:(id)fp8 subject:(id)fp12 body:(id)fp16;
- (void)launchMailAppOnDevice:(id)fp8 subject:(id)fp12 body:(id)fp16;
- (void)displayComposerSheet:(id)fp8 subject:(id)fp12 body:(id)fp16;
- (void)checkDataAvailability:(id)fp8;
- (void)setupPersonData;
- (void)setupPersonViewHeader;
- (void)reloadProfilePhoto;
- (void)viewProfilePhoto:(id)fp8;
- (void)removeHUD;
- (void)showHUD:(id)fp8;
- (id)initWithNibName:(id)fp8 bundle:(id)fp12;
- (id)init;

@end

