/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "/Users/jkb/Work/whatsapp/client/iphone/release/2_10_1/.h"

@class NSArray, NSDictionary, UIBarButtonItem, UILabel, UITableViewCell;

@interface SinglePersonPicker : /Users/jkb/Work/whatsapp/client/iphone/release/2_10_1/
{
    UIBarButtonItem *_buttonCancel;
    UILabel *_labelLoading;
    UITableViewCell *_cellLoading;
    UILabel *_labelNoContacts;
    UITableViewCell *_cellNoContacts;
    NSArray *_sections;
    NSArray *_searchResults;
    NSDictionary *_selectedContact;
    int _numberOfContacts;
    int _pickerMode;
    BOOL _dataAvailable;
    BOOL _showActionCells;
    int _tag;
    id <SinglePersonPickerDelegate> _delegate;
}

- (void)setTag:(int)fp8;
- (int)tag;
- (void)setShowActionCells:(BOOL)fp8;
- (BOOL)showActionCells;
- (void)setPickerMode:(int)fp8;
- (int)pickerMode;
- (void)setDelegate:(id)fp8;
- (id)delegate;
- (void)setCellNoContacts:(id)fp8;
- (id)cellNoContacts;
- (void)setLabelNoContacts:(id)fp8;
- (id)labelNoContacts;
- (void)setCellLoading:(id)fp8;
- (id)cellLoading;
- (void)setLabelLoading:(id)fp8;
- (id)labelLoading;
- (void).cxx_destruct;
- (void)contactsStorageDidUpdateContacts:(id)fp8;
- (void)contactsStorageDidUpdateStatus:(id)fp8;
- (void)alertView:(id)fp8 didDismissWithButtonIndex:(int)fp12;
- (void)searchDisplayControllerDidEndSearch:(id)fp8;
- (void)searchDisplayControllerWillBeginSearch:(id)fp8;
- (BOOL)searchDisplayController:(id)fp8 shouldReloadTableForSearchString:(id)fp12;
- (void)tableView:(id)fp8 didSelectRowAtIndexPath:(id)fp12;
- (id)tableView:(id)fp8 willSelectRowAtIndexPath:(id)fp12;
- (int)tableView:(id)fp8 editingStyleForRowAtIndexPath:(id)fp12;
- (id)tableView:(id)fp8 cellForRowAtIndexPath:(id)fp12;
- (float)tableView:(id)fp8 heightForRowAtIndexPath:(id)fp12;
- (float)tableView:(id)fp8 heightForHeaderInSection:(int)fp12;
- (int)tableView:(id)fp8 sectionForSectionIndexTitle:(id)fp12 atIndex:(int)fp16;
- (id)sectionIndexTitlesForTableView:(id)fp8;
- (id)tableView:(id)fp8 titleForHeaderInSection:(int)fp12;
- (int)tableView:(id)fp8 numberOfRowsInSection:(int)fp12;
- (int)numberOfSectionsInTableView:(id)fp8;
- (void)searchWithCriteria:(id)fp8;
- (void)willAnimateRotationToInterfaceOrientation:(int)fp8 duration:(double)fp12;
- (BOOL)shouldAutorotateToInterfaceOrientation:(int)fp8;
- (void)viewDidDisappear:(BOOL)fp8;
- (void)viewDidAppear:(BOOL)fp8;
- (void)viewWillAppear:(BOOL)fp8;
- (void)viewDidUnload;
- (void)viewDidLoad;
- (void)cancelAction:(id)fp8;
- (void)checkDataAvailability:(id)fp8;
- (void)setupDisplayList;
- (void)updateTableHeader;
- (BOOL)displayActionButtons;
- (BOOL)displaySearchBar;
- (void)saveTableScrollPosition;
- (void)restoreTableScrollPosition;
- (void)dealloc;
- (id)init;
- (id)initWithDelegate:(id)fp8;

@end

